---
title: "This American R"
author: "Chris Cote"
date: '2020-02-14'
slug: this-american-r
categories: Text
---
```{r setup, message = FALSE, warning = FALSE, echo = TRUE}
library(tidyverse)
theme_cc <- theme(panel.grid = element_line(color = "gray90"),
        panel.background = element_blank(),
        plot.background = element_blank())

```

```{r read_data, message = FALSE, warning = FALSE, echo = TRUE}
tal <- read_csv("~/Documents/HKS/rtutorial/data/this_american_life/tal_complete.csv")
```

```{r, message = FALSE, warning = FALSE, echo = TRUE}
tal1 <- tal %>% slice(1)

```


```{r, message = FALSE, warning = FALSE, echo = TRUE}
tal_tidy <- tal %>% slice(1:100) %>%  
  tidytext::unnest_tokens("word", content) %>% 
  mutate(title = str_replace_all(title, "\\\n", " ") %>% 
           str_replace(., "Transcript.+Originally aired.+", "")) %>% 
  anti_join(tidytext::stop_words)
```



```{r, message = FALSE, warning = FALSE, echo = TRUE}
tal_tf_idf <- tal_tidy  %>% 
  select(title, word) %>% 
  group_by(title) %>% 
  count(word, sort = TRUE) %>% 
  ungroup() %>% 
  tidytext::bind_tf_idf(word, title, n)
  
```


```{r fig.height=20, fig.width = 7, message = FALSE, warning = FALSE, echo = TRUE}
tal_tf_idf %>% 
  group_by(title) %>% 
  arrange(-tf_idf) %>% 
  slice(1:10) %>% 
  summarise(top_words = str_c(word, collapse = ", ")) %>% 
  ungroup() %>% 
  left_join(tal_tidy %>% 
  distinct(title, air_date, show_number)) %>% 
  arrange(air_date) %>% 
  mutate(title_words = str_c(title, top_words, sep = ": ")) %>% 
  ggplot() + 
  geom_text(aes(-show_number, -5, label = title_words), size = 5, hjust = 0) + 
  # scale_x_date(date_labels = "%y-%m-%d") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  coord_flip() + 
  scale_y_continuous(limits = c(-6, 6)) +
  labs(x = NULL, y = NULL, title = "Episode Title and Unique Words")+
  NULL
```

```{r, message = FALSE, warning = FALSE, echo = TRUE}
tt <- tal_tf_idf %>% 
  arrange(-tf_idf) %>% 
  group_by(word) %>% 
  mutate(total_n = sum(n)) %>% 
  ungroup()

tt %>% 
  group_by(word) %>% 
  mutate(total_shows = n()) %>% 
  ungroup() %>% 
  filter(tf_idf > 0.035,
         total_shows > 1) %>% 
  ggplot(aes(tf_idf, total_n)) + 
  geom_point(aes(size = total_shows, alpha = tf_idf), shape = 21) +
  ggrepel::geom_text_repel(aes(label = word), size = 3) +
  scale_y_log10() +
  theme_cc

```


### How frequently is David Sedaris on TAL?

David Sedaris is a frequent guest on This American Life, but how frequent?

The chart below shows time between each episode that features David Sedaris.


```{r, message = FALSE, warning = FALSE, echo = TRUE}
tal %>% filter(str_detect(content, regex("sedaris",ignore_case = TRUE))) %>%   tidytext::unnest_tokens("word", content) %>% 
  filter(word == "sedaris") %>% 
  group_by(show_number, air_date) %>% 
  count() %>% 
  ungroup() %>% 
  arrange(air_date) %>% 
  mutate(time_between = as.numeric(air_date - lag(air_date))) %>% 
  ggplot(aes(show_number, time_between)) +
  geom_point() +
  geom_line() +
  theme_cc +
  labs(title = "Where's David?", x = "Show Number", y = "Days since Last Sedaris Appearance")
```

